### ISSUE TITLE
Add allow_nil? option to required attributes

### ISSUE THREAD

**Issue by taylorthurlow** [taylorthurlow/interaktor#2]
Adding an option to accept nil values for required attributes would be good. The way to check for this would be the presence of the key in the attribute hash rather than the value itself.

**Comment by blafri** [comment]
Hey @taylorthurlow not sure if you want to add a dependency to this project but if you dont mind adding a dependency I think [Dry-Schema](https://dry-rb.org/gems/dry-schema/1.5/) will work well for defining your attributes rather than doing the implemenation from scratch. It also has the added benefit of handling coercion of the value to the correct type.
It has all the logic for required and optional values and also allowing nil values which this issue is about. You can simply call success? on the result to see if the provided hash passed all checks and if it did not it returns really nice errors to say what is wrong with the supplied data. I know it will add a dependency to you project which is not always the best thing but check it out as it may work well with this project.

From the intro for the gem

```ruby
UserSchema = Dry::Schema.Params do
  required(:name).filled(:string)
  optional(:email).filled(:string)

  required(:age).maybe(:integer)

  required(:address).hash do
    required(:street).filled(:string)
    required(:city).filled(:string)
    required(:zipcode).filled(:string)
  end
end

result = UserSchema.call(
  name: 'Jane',
  email: 'jane@doe.org',
  address: { street: 'Street 1', city: 'NYC', zipcode: '1234' }
)

result.success?
#=> false
result.errors
#=>errors object
```

**Comment by taylorthurlow** [comment]
Thanks for the tip, I'm going to play around with this for sure. I definitely don't want to take on any dependencies that aren't extremely helpful, but I'll see what the integration would look/feel like and see if it sticks 👍

**Comment by taylorthurlow** [comment]
@blafri Opened a draft PR (#14) if you are at all interested in the changes! I have required and optional attributes moved over right now, working on success and failure attributes. Still not 100% committed to this but we'll see.
